fixed bad logout
konstantinlob/gitalytics.org pull request #133
Opened 2023-03-23 11:14 UTC by roriwa

2023-03-27 11:41 UTC, JuliusJaenchen requested changes

2023-03-27 11:41 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/auth/logout.py
> +    del cookie_storage[CookieKey.ACTIVE_WORKSPACE_ID]
Das sollte eigentlich nicht nötig sein. Hat das bei dir zu einem Fehler geführt?

2023-03-27 12:04 UTC, roriwa commented on src/backend/gitalytics_api/routes/auth/logout.py
> +    del cookie_storage[CookieKey.ACTIVE_WORKSPACE_ID]
wenn du dich ausloggst und dich dann mit einem anderen Provider anmeldest, dann ist immer noch die falsche workspace_id gesetzt. das ist ein sehr unerwünschter fall.

2023-03-30 11:57 UTC, JuliusJaenchen approved these changes

2023-03-30 11:57 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/auth/logout.py
> +    del cookie_storage[CookieKey.ACTIVE_WORKSPACE_ID]
stimmt, danke

2023-03-30 12:04 UTC, merged