Added UI routes
konstantinlob/gitalytics.org pull request #24
Opened 2023-02-12 11:32 UTC by roriwa

2023-02-12 12:44 UTC, JuliusJaenchen requested changes
Top, nur ein paar Vorschläge zur Ordnerstruktur

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/routes/login/index.tsx
> +            <p className="opacity-50 text-center select-none">select the git provider from which you want to login</p>
``
```suggestion
            <p className="opacity-50 text-center select-none">Please log in with your git platform of choice</p>
```

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/AppWrapper.tsx
> +axios.defaults.baseURL = `${baseUrl}/api`;
Können wir hier nicht immer `window.location.origin` benutzen? Jetzt wo wir den Vite development server mit einer production-treuern Umgebung ablösen? Dann muss perspektivisch das Frontend gar nicht mehr wissen, was die Server environment ist.

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/AppWrapper.tsx
> +    const { pathname } = useLocation();
Kann der code auch in den AppWrapper? Also über dem return ();?
Ist ja zum Glück recht wenig code.

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/App.tsx
> +import AboutPage from "./routes/about";
Können wir den "routes" ordner zu "pages" umbenennen?

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/components/Footer.tsx
> +import { Link } from "react-router-dom";
Auf welchen Pages wird jetzt der footer Verwendet? Ich finde alles was auf allen Seiten verwendet werden kann, gehört in den elements ordner, und dann gibt es pro Page Ordner noch einen "components" Ordner für Komponenten, die zu nur der Page gehören.

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/routes/login/index.tsx
> +import GithubIconSrc from "./icons/github.png";
Können wir die Icons gleich in den public ordner legen? Sonst befürchte ich, dass man sie nicht findet, wenn man sie an anderer Stelle benötigt.

2023-02-12 12:44 UTC, JuliusJaenchen commented on src/frontend/src/components/Footer.tsx
> +import { Link } from "react-router-dom";
Diese Struktur verwenden grob bei uns im Team, und es macht das ganze meiner Meinung nach etwas übersichtlicher

2023-02-13 07:57 UTC, konstantinlob approved these changes

2023-02-13 07:57 UTC, JuliusJaenchen approved these changes

2023-02-13 08:09 UTC, merged