setup to add graphs
konstantinlob/gitalytics.org pull request #31
Opened 2023-02-17 20:13 UTC by roriwa

2023-02-18 15:46 UTC, JuliusJaenchen requested changes
Awesome! Ich hatte nur kleine naming-vorschläge.

2023-02-18 15:46 UTC, JuliusJaenchen commented on src/frontend/src/App.tsx
> +                {getAppRoutes()}
```suggestion
                <AppRoutes />
```

2023-02-18 15:46 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/subroutes.tsx
> +export function getAppRoutes() {
```suggestion
export function AppRoutes() {
```

2023-02-18 15:46 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/subroutes.tsx
> +        <Route index element={<NoGraph />} />
```suggestion
        <Route index element={<GraphLandingPage />} />
```
`NoGraph` finde ich gefährlich ähnlich zu `GraphNotFound`. Dacher fände ich das, "DefaultGraph", oder "GraphSelection" ein besseres naming

2023-02-19 14:21 UTC, roriwa commented on src/frontend/src/App.tsx
> +                {getAppRoutes()}
das geht nicht, `<Routes>` kann nur `<Route>` objekte als children haben. deshalb rufe ich es normal auf

2023-02-19 14:22 UTC, roriwa commented on src/frontend/src/pages/app/subroutes.tsx
> +        <Route index element={<NoGraph />} />
mach ich beim nächsten update

2023-02-19 14:48 UTC, JuliusJaenchen approved these changes

2023-02-19 14:48 UTC, merged