Avg per w/d/m
konstantinlob/gitalytics.org pull request #79
Opened 2023-03-04 14:48 UTC by roriwa

2023-03-05 12:14 UTC, JuliusJaenchen requested changes

2023-03-05 12:14 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +        {query.data!.other_workspaces.length && <div className="invisible w-4/5 h-px col-span-3 mx-auto bg-opacity-50 rounded-full group-hover:visible bg-secondary" />}
```suggestion
        {query.data!.other_workspaces.length > 0 && <div className="invisible w-4/5 h-px col-span-3 mx-auto bg-opacity-50 rounded-full group-hover:visible bg-secondary" />}
```
fände ich leichter lesbar

2023-03-05 12:14 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +type Provider = "GITHUB" | "BITBUCKET" | "GITLAB"
```suggestion
enum GitProvider = {
    GITHUB = "GITHUB",
    BITBUCKET = "BITBUCKET",
    GITLAB = "GITLAB",
}
```

2023-03-05 12:14 UTC, JuliusJaenchen commented on src/frontend/src/pages/testing/index.tsx
> +export default function TestPage() {
Soll die TestPage wirklich in den main branch?

2023-03-05 12:14 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/cookies.py
> +    def get(self, key: CookieKey, *, default=None):
```suggestion
    def get(self, key: CookieKey, *, default=None):
```
```suggestion
    def get_or_None(self, key: CookieKey):
        pass
    def get_with_default(self, key: CookieKey, default: any):
```
Aber solange diese methoden nicht gebraucht werden, sehe ich sie eher als Dead code, und würde sie ungerne mit reinnehmen...

2023-03-05 21:48 UTC, roriwa commented on src/backend/gitalytics_api/cookies.py
> +    def get(self, key: CookieKey, *, default=None):
1. ich habe sie erstmal auskommentiert, da sie eine hohe chance zur verwendung hat
2. deine get_or_None + get_or_default ist keine pythonische schreibweise
ps. das `: any` ist kein typ, sondern eine funktion (`any(*args)`). das richtige wäre `typing.Any`

2023-03-05 21:56 UTC, roriwa commented on src/frontend/src/httpStatusIndex.ts
> +    "200": "OK",
ja, aber dann muss man `[HTTP_200_OK]` machen, aber wollre ich nicht, weil dann das ganze formatting verstört wird

2023-03-06 17:08 UTC, JuliusJaenchen requested changes

2023-03-06 17:08 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/get_commits.py
> +        .query(sql.func.sum(subquery.c.count).label("count"),
```suggestion
        .query(sql.func.avg(subquery.c.count).label("avg"),
```

2023-03-06 17:08 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/get_commits.py
> +@router.get("/commits-per-day-in-month")
```suggestion
@router.get("/average-commits-per-day-in-month")
```

2023-03-07 13:39 UTC, JuliusJaenchen requested changes

2023-03-07 13:39 UTC, JuliusJaenchen commented on src/frontend/src/elements/BackendLink.tsx
> +export default function BackendLink(props: PropsWithChildren<JSX.IntrinsicElements["a"]>) {
```suggestion
export default function Link(props: PropsWithChildren<JSX.IntrinsicElements["a"]>) {
```
Das ist ja ein normaler link. Der könnte auch direkt an github oder so gehen...
Wenn ein SPA link hinzukommt würde ich den liebr SpaLink nennen.

2023-03-07 13:39 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +interface GetWorkspaceResponse {
```suggestion
type GetWorkspaceResponse {
```

2023-03-07 13:39 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +        <button className="w-full text-left whitespace-nowrap" onClick={workspace.switch}>
```suggestion
function OtherWorkspace({workspace: WorkspaceType, setWorkspace: (workspaceName: string) => void}) {
    return <>
        <img src={workspace.logo_url} alt="" draggable={false} className="object-contain w-12 h-12 rounded-full mix-blend-color-burn" />
        <button className="w-full text-left whitespace-nowrap" onClick={setWorkspace(workspace.name)}>
```

2023-03-07 13:39 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +function ActiveWorkspace(workspace: WorkspaceType) {
```suggestion
function ActiveWorkspace({workspace: WorkspaceType}) {
```

2023-03-07 13:39 UTC, JuliusJaenchen commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +        <ActiveWorkspace {...query.data!.active_workspace} />
```suggestion
        <ActiveWorkspace workspace={query.data!.active_workspace} />
```

2023-03-07 13:43 UTC, roriwa commented on src/frontend/src/pages/app/menubar/Workspaces.tsx
> +interface WorkspaceType {
ich hatte das `Type` hinzugefügt, damit man es nicht mit einem React-Component verwechselt (hatte ich nämlich einmal)

2023-03-07 14:29 UTC, JuliusJaenchen approved these changes

2023-03-07 14:29 UTC, merged